
--Q1:
SELECT NV.MANV,NV.TEN,NV.DCHI,NV.DTHOAI
FROM NHANVIEN NV JOIN KHANANG KN ON NV.MANV=KN.MANV
WHERE KN.MALOAI='B747'

--Q2:
SELECT CB.MACB, LB.NGAYDI
FROM CHUYENBAY CB JOIN LICHBAY LB ON CB.MACB=LB.MACB
WHERE  CB.GIODI >= '14:00' AND CB.GIODI <='18:00' AND CB.SBDI='DCA' 

--Q3: 
SELECT DISTINCT NV.TEN
FROM CHUYENBAY CB JOIN PHANCONG PC ON PC.MACB=CB.MACB JOIN NHANVIEN NV ON NV.MANV=PC.MANV
WHERE CB.MACB='100'AND CB.SBDI='SLC'

--Q4:
SELECT DISTINCT LB.MALOAI,LB.SOHIEU
FROM LICHBAY LB JOIN CHUYENBAY CB ON CB.MACB=LB.MACB
WHERE CB.SBDI='MIA'

--Q5:
SELECT DC.MACB, DC.NGAYDI, KH.TEN,KH.DCHI,KH.DTHOAI
FROM DATCHO DC JOIN KHACHHANG KH ON DC.MAKH=KH.MAKH
ORDER BY DC.MACB ASC,DC.NGAYDI DESC

--Q6:
SELECT PC.MACB, PC.NGAYDI, NV.TEN,NV.DCHI,NV.DTHOAI
FROM PHANCONG PC JOIN NHANVIEN NV ON PC.MANV=NV.MANV
ORDER BY PC.MACB ASC,PC.NGAYDI DESC

--Q7: 
SELECT CB.MACB,PC.NGAYDI,NV.MANV,NV.TEN
FROM CHUYENBAY CB JOIN PHANCONG PC ON CB.MACB=PC.MACB JOIN NHANVIEN NV ON NV.MANV=PC.MANV 
WHERE CB.SBDEN='ORD'

--Q8
SELECT PC.MACB,PC.NGAYDI,NV.TEN
FROM PHANCONG PC JOIN NHANVIEN NV ON NV.MANV=PC.MANV 
WHERE PC.MANV='1001'
--Q9:
SELECT CB.MACB,CB.SBDI,CB.GIODI,CB.GIODEN,LB.NGAYDI
FROM CHUYENBAY CB JOIN LICHBAY LB ON CB.MACB=LB.MACB
WHERE CB.SBDEN='DEN'
ORDER BY LB.NGAYDI DESC,CB.SBDI ASC

--Q10:
SELECT NV.TEN,LMB.HANGSX,LMB.MALOAI
FROM NHANVIEN NV LEFT JOIN KHANANG KN ON NV.MANV=KN.MANV JOIN LOAIMB LMB ON KN.MALOAI=LMB.MALOAI

--Q11:
SELECT NV.MANV,NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV
WHERE PC.MACB='100' AND PC.NGAYDI='11/01/2000'

--Q12:
SELECT CB.MACB,PC.MANV,NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV JOIN  CHUYENBAY CB ON CB.MACB=PC.MACB
WHERE CB.GIODI='20:30' AND CB.SBDI='MIA' AND PC.NGAYDI='10/31/2000'

--Q13:
SELECT LB.MACB,LB.SOHIEU,LB.MALOAI,LMB.HANGSX
FROM NHANVIEN NV JOIN PHANCONG PC ON PC.MANV=NV.MANV JOIN LICHBAY LB ON LB.MACB=PC.MACB JOIN LOAIMB LMB ON LMB.MALOAI=LB.MALOAI
WHERE NV.TEN='QUANG'

--Q14:
 SELECT NV.TEN
 FROM NHANVIEN NV
 WHERE (NV.MANV NOT IN (SELECT PC.MANV FROM PHANCONG PC))

 --Q15:
 SELECT DISTINCT KH.TEN
 FROM KHACHHANG KH, LOAIMB LMB, LICHBAY LB, DATCHO DC, CHUYENBAY CB
 WHERE (LMB.HANGSX = 'BOEING' AND LB.MALOAI = LMB.MALOAI AND DC.MAKH = KH.MAKH AND DC.MACB = LB.MACB AND DC.NGAYDI = LB.NGAYDI AND CB.MACB = LB.MACB )

 --Q16:
  SELECT DISTINCT LB.MACB
 FROM LICHBAY LB
 WHERE LB.SOHIEU = 10 AND LB.MALOAI = 'B747'