use master
go
use QL_CHUYENBAY
go
--Q34. Cho biết hãng sản xuất, mã loại và số hiệu của máy bay đã được sử dụng nhiều nhất.
SELECT L.HANGSX,L.MALOAI,LB.SOHIEU
FROM LOAIMB L, LICHBAY LB, MAYBAY MB
WHERE L.MALOAI=LB.MALOAI AND MB.MALOAI=LB.MALOAI AND MB.SOHIEU=LB.SOHIEU
GROUP BY L.HANGSX,L.MALOAI,LB.SOHIEU 
HAVING COUNT (*) >= ALL (SELECT COUNT (*)
FROM LICHBAY LB, MAYBAY MB, LOAIMB L
WHERE  L.MALOAI=LB.MALOAI AND MB.MALOAI=LB.MALOAI AND MB.SOHIEU=LB.SOHIEU
GROUP BY L.HANGSX,L.MALOAI,LB.SOHIEU )

--Q35. Cho biết tên nhân viên được phân công đi nhiều chuyến bay nhất. 

SELECT NV.TEN
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV=PC.MANV
GROUP BY NV.TEN, NV.MANV
HAVING COUNT(*) = (SELECT MAX(SLCB)
FROM (SELECT COUNT(PC.MACB) AS SLCB
FROM PHANCONG PC, NHANVIEN NV
WHERE NV.MANV=PC.MANV
GROUP BY NV.TEN, NV.MANV)AS  T)

--Q36. Cho biết thông tin của phi công (tên, địa chỉ, điện thoại) lái nhiều chuyến bay nhất.

SELECT NV.TEN, NV.DCHI, NV.DTHOAI, COUNT(PC.MANV) AS SL
FROM NHANVIEN NV JOIN PHANCONG PC ON  NV.MANV=PC.MANV 
WHERE NV.LOAINV=1
GROUP BY NV.TEN, NV.DCHI, NV.DTHOAI
HAVING COUNT(PC.MANV) >= ALL (SELECT COUNT(PC.MANV)
FROM PHANCONG PC, NHANVIEN NV
WHERE NV.MANV=PC.MANV AND NV.LOAINV=1
GROUP BY NV.MANV)
--Q37. Cho biết sân bay (SBDEN) và số lượng chuyến bay của sân bay có ít chuyến bay đáp xuống nhất.
SELECT CB.SBDEN, COUNT(CB.MACB) AS SLCB
FROM CHUYENBAY CB
GROUP BY CB.SBDEN
HAVING COUNT(CB.SBDEN) <= ALL(SELECT COUNT( CB1.SBDEN)
FROM CHUYENBAY CB1
GROUP BY CB1.MACB)

--Q38. Cho biết sân bay (SBDI) và số lượng chuyến bay của sân bay có nhiều chuyến bay xuất phát nhất. 
SELECT CB.SBDI, COUNT(CB.MACB) AS SLCB
FROM CHUYENBAY CB
GROUP BY CB.SBDI
HAVING COUNT(CB.SBDI) >= ALL(SELECT COUNT(CB.SBDI)
FROM CHUYENBAY CB GROUP BY CB.SBDI)

--Q39. Cho biết tên, địa chỉ, và điện thoại của khách hàng đã đi trên nhiều chuyến bay nhất.
SELECT TEN, DCHI, DTHOAI
FROM KHACHHANG KH, DATCHO DC
WHERE KH.MAKH=DC.MAKH
GROUP BY DC.MAKH, KH.TEN, KH.DCHI, KH.DTHOAI
HAVING COUNT(DC.MAKH) >= ALL (SELECT COUNT(DC.MAKH) FROM DATCHO DC GROUP BY DC.MAKH)

--Q40. Cho biết mã số, tên và lương của các phi công có khả năng lái nhiều loại máy bay nhất.

SELECT NV.MANV, NV.TEN, NV.LUONG
FROM NHANVIEN NV JOIN KHANANG KN ON  NV.MANV=KN.MANV 
WHERE NV.LOAINV=1
GROUP BY NV.MANV, NV.TEN, NV.LUONG
HAVING COUNT(NV.MANV) >= ALL (SELECT COUNT(NV.MANV)
FROM KHANANG KN, NHANVIEN NV
WHERE NV.MANV=KN.MANV AND NV.LOAINV=1
GROUP BY NV.MANV)
--Q41. Cho biết thông tin (mã nhân viên, tên, lương) của nhân viên có mức lương cao nhất. 
SELECT NV.MANV, NV.TEN, NV.LUONG
FROM NHANVIEN NV
WHERE LUONG >= ALL(SELECT LUONG FROM NHANVIEN NV)
--Q42. Cho biết tên, địa chỉ của các nhân viên có lương cao nhất trong phi hành đoàn (các nhân viên được phân công trong một chuyến bay) mà người đó tham gia.
SELECT DISTINCT NV.TEN, NV.DCHI, PC.MACB
FROM NHANVIEN NV JOIN PHANCONG PC ON  NV.MANV=PC.MANV 
WHERE LUONG >= ALL( SELECT LUONG FROM NHANVIEN NV, PHANCONG PC WHERE NV.MANV=PC.MANV)

--Q43. Cho biết mã chuyến bay, giờ đi và giờ đến của chuyến bay bay sớm nhất trong ngày. 
SELECT CB.MACB, CB.GIODI, CB.GIODEN, LB.NGAYDI
FROM CHUYENBAY CB JOIN LICHBAY LB ON CB.MACB=LB.MACB 
WHERE EXISTS
( SELECT *
FROM CHUYENBAY CB1 JOIN LICHBAY LB1 ON CB1.MACB=LB1.MACB
WHERE  LB.NGAYDI=LB1.NGAYDI GROUP BY LB1.NGAYDI HAVING CB.GIODI=MIN(CB1.GIODI))

--Q44. Cho biết mã chuyến bay có thời gian bay dài nhất. Xuất ra mã chuyến bay và thời gian bay (tính bằng phút).
SELECT CB.MACB, DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) AS THOIGIANBAY
FROM CHUYENBAY CB
WHERE DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) >= ALL( SELECT DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) FROM CHUYENBAY CB)
--Q45. Cho biết mã chuyến bay có thời gian bay ít nhất. Xuất ra mã chuyến bay và thời gian bay.
SELECT CB.MACB, DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) AS THOIGIANBAY
FROM CHUYENBAY CB
WHERE DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) <= ALL( SELECT DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) FROM CHUYENBAY CB)
--Q46. Cho biết mã chuyến bay và ngày đi của những chuyến bay bay trên loại máy bay B747 nhiều nhất.
SELECT LB.MACB, LB.NGAYDI 
FROM LICHBAY LB
WHERE EXISTS( SELECT * FROM LICHBAY LB1
WHERE LB1.MACB=LB.MACB AND LB1.MALOAI='B747' GROUP BY MACB
HAVING COUNT(LB1.NGAYDI) >= ALL(SELECT COUNT(LB2.NGAYDI) FROM  LICHBAY LB2 WHERE LB2.MALOAI='B747' GROUP BY LB2.MACB))

--Q47. Với mỗi chuyến bay có trên 3 hành khách, cho biết mã chuyến bay và số lượng nhân viên trên chuyến bay đó. Xuất ra mã chuyến bay và số lượng nhân viên.
SELECT LB.MACB, COUNT(DISTINCT PC.MANV) SLNV
FROM DATCHO DC JOIN LICHBAY LB ON DC.MACB = LB.MACB AND DC.NGAYDI = LB.NGAYDI JOIN PHANCONG PC ON PC.NGAYDI = LB.NGAYDI AND PC.MACB = LB.MACB
GROUP BY LB.MACB, LB.NGAYDI
HAVING COUNT(DISTINCT DC.MAKH) > 3
 
--Q48. Với mỗi loại nhân viên có tổng lương trên 600000, cho biết số lượng nhân viên trong từng loại nhân viên đó. Xuất ra loại nhân viên, và số lượng nhân viên tương ứng.
SELECT NV.LOAINV, COUNT(MANV) AS SLNV
FROM NHANVIEN NV
GROUP BY NV.LOAINV
HAVING SUM(NV.LUONG) > 600000
--Q49. Với mỗi chuyến bay có trên 3 nhân viên, cho biết mã chuyến bay và số lượng khách hàng đã đặt chỗ trên chuyến bay đó. 
SELECT LB.MACB, COUNT(DISTINCT DC.MAKH) SLHK
FROM DATCHO DC JOIN LICHBAY LB ON DC.MACB = LB.MACB AND DC.NGAYDI = LB.NGAYDI JOIN PHANCONG PC ON PC.NGAYDI = LB.NGAYDI AND PC.MACB = LB.MACB
GROUP BY LB.MACB, LB.NGAYDI
HAVING COUNT(DISTINCT PC.MANV) > 3
--Q50. Với mỗi loại máy bay có nhiều hơn một chiếc, cho biết số lượng chuyến bay đã được bố trí bay bằng loại máy bay đó. Xuất ra mã loại và số lượng.
SELECT LB.MALOAI, COUNT(LB.MACB) SLCB
FROM LICHBAY LB
WHERE LB.MALOAI IN (SELECT MB.MALOAI FROM MAYBAY MB GROUP BY MB.MALOAI HAVING COUNT(MB.SOHIEU) > 1)
GROUP BY LB.MALOAI