--tạo csdl
USE master 
GO --KHỐI LỆNH KẾT THÚC TRƯỚC
IF DB_ID('DIEMTHAMQUAN') IS NOT NULL 
	DROP DATABASE DIEMTHAMQUAN
GO
CREATE DATABASE DIEMTHAMQUAN
GO
USE DIEMTHAMQUAN
GO
CREATE TABLE TINH_THANH
(
QUOCGIA CHAR(5),
MATINHTHANH CHAR(5),
DANSO INT,
DIENTICH FLOAT,
TENTT NVARCHAR(30)

--KHAI BÁO PK
	CONSTRAINT PK_TINH_THANH
	PRIMARY KEY (MATINHTHANH)
)
CREATE TABLE DIEM_THAM_QUAN
(
MADTQ CHAR(10),
TENDTQ NVARCHAR(30),
TINHTHANH CHAR(5),
QUOCGIA CHAR(5),
DACDIEM NVARCHAR(50)

--KHAI BÁO PK
	CONSTRAINT PK_DIEM_THAM_QUAN
	PRIMARY KEY (MADTQ)
)
CREATE TABLE QUOC_GIA
(
MAQG CHAR(5),
TENQG NVARCHAR(20),
THUDO CHAR(5),
DANSO INT,
DIENTICH FLOAT
--KHAI BÁO PK
	CONSTRAINT PK_QUOC_GIA
	PRIMARY KEY (MAQG)
)
--TẠO KHÓA NGOẠI
ALTER TABLE TINH_THANH
ADD
CONSTRAINT FK_TT_QG
FOREIGN KEY (QUOCGIA)
REFERENCES QUOC_GIA(MAQG)

ALTER TABLE QUOC_GIA
ADD 
CONSTRAINT FK_QG_TT
FOREIGN KEY(THUDO)
REFERENCES TINH_THANH(MATINHTHANH)

ALTER TABLE DIEM_THAM_QUAN
ADD
CONSTRAINT FK_DTQ_TT
FOREIGN KEY(TINHTHANH)
REFERENCES TINH_THANH(MATINHTHANH),

CONSTRAINT FK_DTQ_QG
FOREIGN KEY(QUOCGIA)
REFERENCES QUOC_GIA(MAQG)

INSERT INTO DIEM_THAM_QUAN(MADTQ,TENDTQ,TINHTHANH,QUOCGIA,DACDIEM)
VALUES
('DTQ001',N'VĂN MIẾU',NULL,NULL,N'DI TÍCH CỔ'),
('DTQ002',N'HOÀNG LĂNG',NULL,NULL,N'DI TÍCH CỔ'),
('DTQ003',N'THÁP TOKYO',NULL,NULL,N'CÔNG TRÌNH HIỆN ĐẠI')

INSERT INTO QUOC_GIA(MAQG,TENQG,THUDO,DANSO,DIENTICH)
VALUES
('QG001',N'VIỆT NAM',NULL,115000000,331688.00),
('QG002',N'NHẬT BẢN',NULL,129500000,337834.00)

INSERT INTO TINH_THANH(QUOCGIA,MATINHTHANH,DANSO,DIENTICH,TENTT)
VALUES
(null,'TT001',2500000,927.39,N'HÀ NỘI'),
(null,'TT002',5344000,5009.00,N'HUẾ'),
(null,'TT003',12084000,2187.00,N'TOKYO')

UPDATE QUOC_GIA
SET THUDO='TT001'
WHERE MAQG='QG001'
UPDATE QUOC_GIA
SET THUDO='TT003'
WHERE MAQG='QG002'

UPDATE DIEM_THAM_QUAN
SET TINHTHANH='TT001'
WHERE MADTQ='DTQ001'
UPDATE DIEM_THAM_QUAN
SET TINHTHANH='TT002'
WHERE MADTQ='DTQ002'
UPDATE DIEM_THAM_QUAN
SET TINHTHANH='TT003'
WHERE MADTQ='DTQ003'

UPDATE DIEM_THAM_QUAN
SET QUOCGIA='QG001'
WHERE MADTQ='DTQ001'
UPDATE DIEM_THAM_QUAN
SET QUOCGIA='QG001'
WHERE MADTQ='DTQ002'
UPDATE DIEM_THAM_QUAN
SET QUOCGIA='QG002'
WHERE MADTQ='DTQ003'

UPDATE TINH_THANH
SET QUOCGIA='QG001'
WHERE MATINHTHANH='TT001'

UPDATE TINH_THANH
SET QUOCGIA='QG001'
WHERE MATINHTHANH='TT002'

UPDATE TINH_THANH
SET QUOCGIA='QG002'
WHERE MATINHTHANH='TT003'
SELECT*
FROM DIEM_THAM_QUAN
SELECT*
FROM QUOC_GIA

SELECT*
FROM TINH_THANH

SELECT DTQ.MADTQ,DTQ.TENDTQ,TT.DIENTICH/QG.DIENTICH AS N'TỈ LỆ DIỆN TÍCH'
FROM DIEM_THAM_QUAN DTQ JOIN TINH_THANH TT ON DTQ.TINHTHANH=TT.MATINHTHANH JOIN QUOC_GIA QG ON QG.MAQG=TT.QUOCGIA
WHERE (TT.DIENTICH/QG.DIENTICH) > 0.01

SELECT QG.TENQG,QG.MAQG
FROM QUOC_GIA QG JOIN TINH_THANH TT ON QG.MAQG=TT.QUOCGIA
GROUP BY QG.TENQG,QG.MAQG
HAVING COUNT(TT.MATINHTHANH) >30